spring.jpa.database: "MYSQL"
spring.datasource.platform: "MYSQL"
spring.jpa.show-sql: "false"
spring.database.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://ec2-3-85-165-145.compute-1.amazonaws.com:3306/roadrunner_consulta"
spring.datasource.username: "coyote"
spring.datasource.password: "Pas$w0rd"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL8Dialect"
server:
   port: 8080  
spring:
  eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://ec2-54-208-198-150.compute-1.amazonaws.com:8761/eureka     
