spring.jpa.database: "MYSQL"
spring.datasource.platform: "MYSQL"
spring.jpa.show-sql: "false"
spring.database.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://localhost:3306/roadrunner_crm"
spring.datasource.username: "root"
spring.datasource.password: "SuperD0g"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL8Dialect"
server:
   port: 8082  
spring:
  cloud:
    stream:
      bindings:
        output:
            destination:  chamadoAbertoTopic
            content-type: application/json
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost        
  eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka    
